### ISSUE TITLE
Item Pipe interaction causing client crash

### ISSUE THREAD

**Issue by seth0h** [FlexibleGames/VintageEngineering#13]
When adding or removing item pipe segments, the client is crashing. The below log is in reference to the removal of a pipe segment. The pipe assembly worked as expected for a while then stopped transporting items it previously transported. Some segments of the item pipe were removable, but the segments that remain cause a client crash.

![item_pipes_config_2024-11-01](https://github.com/user-attachments/assets/fa6d3bb2-5fed-4065-99f1-f6d44ba272be)

Running on 64 bit Windows 10.0.17763.0 with 32727 MB RAM
Game Version: v1.19.8 (Stable)
11/1/2024 8:36:26 AM: Critical error occurred in the following mod: vintageengineering@0.3.0
Loaded Mods: degrees1499@1.0.0, acorns@0.5.3, aculinaryartillery@1.1.5, arrowheadsrecovery@1.0.1, autopanning@1.0.1, axleinblocks@1.19.8-rc.1, bf@0.0.1, bettersticks@1.1.0, CredClasses@1.0.0, capreolinae@1.1.5, casuariidae@1.0.8, pantherinae@1.1.9, rhinocerotidae@1.0.3, sirenia@1.0.5, mastodontrunk@1.0.1, millwright@1.1.7, moreundergarments@0.0.1, mbpc@1.0.1, moremolds@1.4.2, palisademod@1.1.0, primitivesurvival@3.6.4, orcmod@1.2.4, nvscaffolding@1.0.1, spidersilk@1.2.2, swordz@1.1.8, litbrig@0.5.0, vintageengineering@0.3.0, game@1.19.8, accessibilitytweaks@3.7.1, alchemy@1.6.35, animalcages@3.0.3, betterfirepit@1.1.4, betterruins@0.3.7, blocksoverlay@3.2.4, carryon@1.7.4, commonlib@2.5.0-rc.2, danatweaks@3.2.2, easylightlevels@1.0.3, expandedfoods@1.7.0, extrainfo@1.8.1, fromgoldencombs@1.6.3, harphoh@1.1.0, hit@2.1.1, hudclock@3.4.0, hydrateordiedrate@1.2.8, improvedhandbookrecipes@1.0.0, leaderboards@1.1.6, mobsradar@2.1.1, moreanimals@1.3.5, morebags@1.2.0, moreplaster@1.0.2, noticeboard@0.6.0, onebedsleeping@2.4.1, petai@2.2.6, playerlist@2.1.4, prospecttogether@1.4.0-rc.1, roadworks@2.0.0, sharablewaypoints@1.5.4, th3dungeon@0.2.1, creative@1.19.8, vsimgui@1.1.5, survival@1.19.8, wildfarmingrevival@1.2.5, configlib@1.3.13, em@2.7.0, foxtaming@1.4.0, playercorpse@1.10.1-rc.1, cookie12000stickbeam@1.1.0, stonequarry@3.3.1, wolftaming@2.1.3, bricklayers@2.5.6, entitiesconfiguration@1.0.9
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.InventoryBase.DropAll(Vec3d pos, Int32 maxStackSize) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 770
   at VintageEngineering.Transport.PipeExtractionNode.DropContents(Vec3d atPos) in C:\_Programming\Vintage\VintageEngineering\code\VintageEngineering\Transport\PipeExtractionNode.cs:line 276
   at VintageEngineering.Transport.PipeExtractionNode.OnNodeRemoved() in C:\_Programming\Vintage\VintageEngineering\code\VintageEngineering\Transport\PipeExtractionNode.cs:line 212
   at VintageEngineering.Transport.API.BEPipeBase.MarkPipeDirty(IWorldAccessor world, Boolean dirtyshape) in C:\_Programming\Vintage\VintageEngineering\code\VintageEngineering\Transport\API\BEPipeBase.cs:line 497
   at VintageEngineering.Transport.BlockPipeBase.OnNeighbourBlockChange(IWorldAccessor world, BlockPos pos, BlockPos neibpos) in C:\_Programming\Vintage\VintageEngineering\code\VintageEngineering\Transport\BlockPipeBase.cs:line 66
   at Vintagestory.Client.NoObf.ClientMain.TriggerNeighbourBlocksUpdate(BlockPos pos) in VintagestoryLib\Client\ClientMain.cs:line 3252
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection) in VintagestoryLib\Client\ClientMain.cs:line 1697
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 785
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 444
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/5/2024 9:48:04 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x624
Faulting application start time: 0x01db1765976906fb
Faulting application path: C:\Users\<username>\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\<username>\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: c2e6517f-fd2f-4f73-b377-f5f42ea27430
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/21/2024 5:35:43 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0xf3c
Faulting application start time: 0x01db0c6e089fcd86
Faulting application path: C:\Users\<username>\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\<username>\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 0ae8a93e-bf33-4e7f-bedb-2bbf81578582
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/21/2024 5:34:24 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x1f10
Faulting application start time: 0x01db0c6d47b90e32
Faulting application path: C:\Users\<username>\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\<username>\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: f36fe31f-e3c4-4642-a56b-489f7819f123
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by FlexibleGames** [comment]
So the fault is in:
at VintageEngineering.Transport.PipeExtractionNode.DropContents(Vec3d atPos)

I see only one extraction node in that screen shot. Are you getting the crash when trying to break ANY pipe in that shot or just the extraction node?

**Comment by Vaemas** [comment]
> So the fault is in: at VintageEngineering.Transport.PipeExtractionNode.DropContents(Vec3d atPos)
> 
> I see only one extraction node in that screen shot. Are you getting the crash when trying to break ANY pipe in that shot or just the extraction node?

Any pipe. Not just the extraction node.

**Comment by Vaemas** [comment]
Crash log when right clicking on the extraction node itself (literally just that, no other interaction with the extraction node).

Running on 64 bit Windows 10.0.17763.0 with 32727 MB RAM
Game Version: v1.19.8 (Stable)
11/1/2024 1:58:05 PM: Critical error occurred in the following mod: vintageengineering@0.3.0
Loaded Mods: degrees1499@1.0.0, acorns@0.5.3, aculinaryartillery@1.1.5, arrowheadsrecovery@1.0.1, autopanning@1.0.1, axleinblocks@1.19.8-rc.1, bf@0.0.1, bettersticks@1.1.0, CredClasses@1.0.0, capreolinae@1.1.5, casuariidae@1.0.8, pantherinae@1.1.9, rhinocerotidae@1.0.3, sirenia@1.0.5, mastodontrunk@1.0.1, millwright@1.1.7, moreundergarments@0.0.1, mbpc@1.0.1, moremolds@1.4.2, palisademod@1.1.0, primitivesurvival@3.6.4, orcmod@1.2.4, nvscaffolding@1.0.1, spidersilk@1.2.2, swordz@1.1.8, litbrig@0.5.0, vintageengineering@0.3.0, game@1.19.8, accessibilitytweaks@3.7.1, alchemy@1.6.35, animalcages@3.0.3, betterfirepit@1.1.4, betterruins@0.3.7, blocksoverlay@3.2.4, carryon@1.7.4, commonlib@2.5.0-rc.2, danatweaks@3.2.2, easylightlevels@1.0.3, expandedfoods@1.7.0, extrainfo@1.8.1, fromgoldencombs@1.6.3, harphoh@1.1.0, hit@2.1.1, hudclock@3.4.0, hydrateordiedrate@1.2.8, improvedhandbookrecipes@1.0.0, leaderboards@1.1.6, mobsradar@2.1.1, moreanimals@1.3.5, morebags@1.2.0, moreplaster@1.0.2, noticeboard@0.6.0, onebedsleeping@2.4.1, petai@2.2.6, playerlist@2.1.4, prospecttogether@1.4.0-rc.1, roadworks@2.0.0, sharablewaypoints@1.5.4, th3dungeon@0.2.1, creative@1.19.8, vsimgui@1.1.5, survival@1.19.8, wildfarmingrevival@1.2.5, configlib@1.3.13, em@2.7.0, foxtaming@1.4.0, playercorpse@1.10.1-rc.1, cookie12000stickbeam@1.1.0, stonequarry@3.3.1, wolftaming@2.1.3, bricklayers@2.5.6, entitiesconfiguration@1.0.9
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.InventoryBase.Open(IPlayer player) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 823
   at Vintagestory.Common.PlayerInventoryManager.OpenInventory(IInventory inventory) in VintagestoryLib\Common\GameContent\Inventory\PlayerInventoryManager.cs:line 353
   at VintageEngineering.Transport.GUIPipeExtraction..ctor(String dialogTitle, InventoryBase inventory, BlockPos blockEntityPos, ICoreClientAPI capi, BEPipeBase bentity, PipeExtractionNode node, Int32 faceindex) in C:\_Programming\Vintage\VintageEngineering\code\VintageEngineering\Transport\GUIPipeExtraction.cs:line 23
   at VintageEngineering.Transport.API.BEPipeBase.<>c__DisplayClass39_0.<OnPlayerRightClick>b__0() in C:\_Programming\Vintage\VintageEngineering\code\VintageEngineering\Transport\API\BEPipeBase.cs:line 428
   at VintageEngineering.Transport.API.BEPipeBase.ToggleExtractionNodeDialog(IPlayer player, Int32 faceindex, CreateDialogDelegate onCreateDialog) in C:\_Programming\Vintage\VintageEngineering\code\VintageEngineering\Transport\API\BEPipeBase.cs:line 863
   at VintageEngineering.Transport.API.BEPipeBase.OnPlayerRightClick(IWorldAccessor world, IPlayer player, BlockSelection selection) in C:\_Programming\Vintage\VintageEngineering\code\VintageEngineering\Transport\API\BEPipeBase.cs:line 426
   at VintageEngineering.Transport.BlockPipeBase.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in C:\_Programming\Vintage\VintageEngineering\code\VintageEngineering\Transport\BlockPipeBase.cs:line 115
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 864
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 444
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/5/2024 9:48:04 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x624
Faulting application start time: 0x01db1765976906fb
Faulting application path: C:\Users\<username>\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\<username>\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: c2e6517f-fd2f-4f73-b377-f5f42ea27430
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/21/2024 5:35:43 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0xf3c
Faulting application start time: 0x01db0c6e089fcd86
Faulting application path: C:\Users\<username>\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\<username>\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 0ae8a93e-bf33-4e7f-bedb-2bbf81578582
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 9/21/2024 5:34:24 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x1f10
Faulting application start time: 0x01db0c6d47b90e32
Faulting application path: C:\Users\<username>\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\<username>\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: f36fe31f-e3c4-4642-a56b-489f7819f123
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by FlexibleGames** [comment]
I suspect this is a client/server issue. For some reason the client isn't being updated properly. 

These are the hardest things to debug. Things that work fine on a single player instance versus a client on a server.
Odd that the system was working fine for awhile and suddenly stopped working though. What changed?

**Comment by Vaemas** [comment]
> This seems to be a chunk boundary issue at its core, will investigate, I apologize for not jumping on this right away as I planned on a 2 month break from active development over the holidays and right when that started this bug came up.

Agreed. Ever since the equipment was restricted to within chunks, no further issue. Enjoy the hiatus!

**Comment by FlexibleGames** [comment]
So I've been combing through the code for the pipes and I have a TON of block and chunk loading calls in there already.
If possible, do you have some way of reliably replicating this bug I could test step-by-step?
Was this bug only happening sometimes, only on a server and not on singleplayer?
Survival or creative mode?
Any other details about this would be most welcome, as of now I could try to fix it, but I may end up causing more bugs than I fix.

**Comment by Vaemas** [comment]
Unfortunately it wasn't reliably replicatable. It happened sometimes, corrupting certain pipe networks (it never affected power networks that we could tell). It was only on a server. Both creative and survival. Regardless of the player's mode, removing an affected pipe node would cause the crash.

**Comment by FlexibleGames** [comment]
I have a MP server up and running now and if this bug presents itself I'll be better able to debug it. I can make sure I cross chunk boundaries with a pipe network.
